### PR TITLE
Update flowcompare.html to fix typo

### PR DESCRIPTION
**Pull request by HaroldPetersInskipp**
Changed "Viusal" to "Visual" on line 21.

### CODE REVIEW

**Comment by HaroldPetersInskipp** [comment]
After installing on a Pi Zero W, a restart was required for me, so I thought a note for others might be nice.

**Comment by gorenje** [comment]
Cheers, I'll push out new version

**Comment by gorenje** [comment]
Btw the reload/restart of Node-RED could also be related to this [issue](https://github.com/node-red/node-red/pull/4484) which was fixed with NR 3.1.4 ... depending on your version, your mileage will vary...

**Comment by HaroldPetersInskipp** [comment]
I was on Node-RED version 4.0.2 and still needed a restart, so I'm not sure it's related to that issue.

**Pull request merged**
